# Generated by Django 2.2 on 2020-03-04 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=django.utils.timezone.now, max_length=200, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
