# Generated by Django 2.2 on 2020-03-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
