# Generated by Django 2.2 on 2020-03-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_auto_20200307_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture',
        ),
    ]
