# Generated by Django 2.2 on 2020-03-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_remove_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_picture', verbose_name='Profile Picture'),
        ),
    ]
