# Generated by Django 2.2 on 2020-03-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_picture/default.png', upload_to='profile_picture', verbose_name='Profile Picture'),
        ),
    ]
