# Generated by Django 2.2 on 2020-03-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0005_auto_20200310_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/default.png', upload_to='profile_picture', verbose_name='Profile Picture'),
        ),
    ]
