# Generated by Django 2.2 on 2020-02-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handouts',
            name='owner',
        ),
    ]
