# Generated by Django 2.2 on 2020-02-27 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0002_remove_handouts_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='handouts',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
